### PR TITLE
Add handlebars partial hash parameters as subexpression support

### LINKED ISSUE #42: Handlebars partial hash are not supported
things like 

```handlebars
{{> 'input' placeholder=(gettext 'type here...') }}
```

### PR DESCRIPTION
**Pull request by JSteunou**
Fixes #42

### CODE REVIEW

**Comment by JSteunou** [comment]
Hi @justinvdm do you have time to review this PR?

**Comment by justinvdm** [comment]
Hi @JSteunou, its been a while :) Thanks for PR and apologies for delay, will try get to this today.

**Comment by JSteunou** [comment]
Been a while for sure, but still using that good old jspot :)

**Comment by justinvdm** [comment]
:+1: looks good :) thanks for all the tests, will merge and release.

Side note: I haven't been keeping track of what new developments might be out there for i18n for js. I think jspot is quite outdated in many ways. For one, it is very common nowadays for people to transpile using tools like babel. Jspot doesn't work well in those cases. unless the person using jspot is extracting on the transpiled code, which may/may not be an acceptable assumption to make. I'm going to try give this all some thought.

**Comment by justinvdm** [comment]
@JSteunou 0.3.13 released :)

**Comment by JSteunou** [comment]
Thank you @justinvdm !!

About es6 or es5 from babel I couldnt tell, still with plain old classic es5. But I think it should work the same with es5 from babel after transpilation.
If some day I have issue with jspot on es6 I will create a PR ;)

**Pull request merged**
