### PR TITLE
Fixes issue with template literal and simple quote

### PR DESCRIPTION
**Pull request by JSteunou**
Sorry @justinvdm I let an issue with my last commit. I replaced template literal by string using simple quote without escaping potential simple quote already inside the template literal.

### CODE REVIEW

**Comment by JSteunou** [comment]
@justinvdm Also I figure out it was silly to use template literal with gettext, because things like

```js
`${foo} is the best`
```

Will add an entry `${foo} is the best` to the .pot whereas the call when running could be anything, like `jspot is the best` which will found no match in the .pot :( 

It is still nice to support template literal for those using template literal *everywhere* even when simple string suffice, but one cannot use it with all its power with gettext, still need a sprintf above.

**Comment by justinvdm** [comment]
@miltontony / @nathanbegbie: hi :) could you perhaps take a look at this?

**Comment by JSteunou** [comment]
@justinvdm @miltontony @nathanbegbie any news?

**Comment by JSteunou** [comment]
@miltontony @nathanbegbie ?

**Comment by nathanbegbie** [comment]
@justinvdm @JSteunou Apologies, I've been on leave and this fell of my radar,taking a look now

**Comment by JSteunou** [comment]
welcome back ;)

**Pull request merged**
